name: CI
run-name: ${{ github.event.inputs.version }}

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

  # Manual trigger for release
  workflow_dispatch:
    inputs:
      version:
        description: 'Release name'
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            decompress: 7z x
            executable_name: Znippets.exe
            wget: C:\msys64\usr\bin\wget.exe
            zig: zig-windows-x86_64-0.14.0
            zig_download: zig-windows-x86_64-0.14.0.zip
          - os: ubuntu-latest
            decompress: tar -xf
            executable_name: Znippets
            wget: wget
            zig: zig-linux-x86_64-0.14.0
            zig_download: zig-linux-x86_64-0.14.0.tar.xz

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Zig
        run: |
            ${{ matrix.wget }} https://ziglang.org/download/0.14.0/${{ matrix.zig_download }}
            ${{ matrix.decompress }} ${{ matrix.zig_download }}
      
      - name: Run tests
        run: make test ZIG=${{ matrix.zig }}/zig

      - name: Install release version
        run: make install ZIG=${{ matrix.zig }}/zig

      - name: Prepare release
        # Only if manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          make doc-check
          make release_changelog.md
          make validate_semver VERSION=${{ github.event.inputs.version }}

      - name: Release
        # Only if manually triggered
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          target_commitish: main
          body_path: release_changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            install/bin/${{ matrix.executable_name }}